"""
Iteration 2: Custom Dictionary Evaluation Pipeline
====================================================
Pipeline:
  0. Load dataset and perform the 80/20 train/test split.
  1. Build the custom dictionary DB from the TRAINING split only.
  2. Evaluate all TEST samples against that custom DB (Egenlagd).
  3. Evaluate all TEST samples against the base FoxIO DB (`ja4+_db.json`).
  4. Generate visual graphs silently (App Distribution, Confusion Matrices, Top-K, Collisions).

Usage:
    python Iteration2/iteration2.py
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(SCRIPT_DIR)
VIZ_DIR    = os.path.join(PARENT_DIR, "Visualization")
sys.path.insert(0, PARENT_DIR)
sys.path.insert(0, VIZ_DIR)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from dictionary_model import JA4PlusDatabase
from generate_comparison_graphs import plot_confusion_matrix, plot_collision_matrix, plot_top_k

# ── Config ────────────────────────────────────────────────────────────────────
DATASET_FILE   = os.path.join(PARENT_DIR, "..", "Create Dictionary", "correlated_ja4_db_large.json")
CUSTOM_DB_FILE = os.path.join(PARENT_DIR, "Custom_DB", "egenlagd_correlated_db.json")
FOXIO_DB_FILE  = os.path.join(PARENT_DIR, "ja4+_db.json")

RESULTS_DIR    = os.path.join(PARENT_DIR, "Results")
EGEN_RESULT_FILE = os.path.join(RESULTS_DIR, "correlated_Egenlagd_result.json")
FOXIO_RESULT_FILE = os.path.join(RESULTS_DIR, "foxio_Egenlagd_result.json")

DICT_MODE      = "ja4_ja4s_ja4ts"
RANDOM_STATE   = 42


# ── Step 0 · Load data, split, and plot distribution ─────────────────────────

def load_split_and_plot(dataset_path: str, random_state: int = RANDOM_STATE):
    with open(dataset_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    df = pd.DataFrame(data).dropna(subset=["application"])
    
    # 0a. Plot Application Distribution (Original Dataset)
    app_counts = df["application"].value_counts().reset_index()
    app_counts.columns = ["Application", "Count"]
    
    plt.figure(figsize=(12, 8))
    ax = sns.barplot(x="Count", y="Application", data=app_counts, palette="viridis")
    for i, v in enumerate(app_counts["Count"]):
        ax.text(v + 1, i, str(v), color='black', va='center')
        
    plt.title(f"Application Distribution in Original Dataset (Total: {len(df)} records)", fontsize=16, pad=15)
    plt.xlabel("Number of Occurrences", fontsize=12)
    plt.ylabel("Application", fontsize=12)
    plt.tight_layout()
    
    dist_out = os.path.join(VIZ_DIR, "app_distribution_large.png")
    plt.savefig(dist_out, dpi=300)
    plt.close()

    # 0b. Perform 80/20 Split
    y = df["application"]
    try:
        train_df, test_df = train_test_split(df, test_size=0.2, random_state=random_state, stratify=y)
    except ValueError:
        train_df, test_df = train_test_split(df, test_size=0.2, random_state=random_state)

    return train_df, test_df


# ── Step 1 · Build the custom DB from the TRAIN split ─────────────────────────

def build_custom_db(train_df: pd.DataFrame, output_db_path: str):
    subset_cols = ["application", "ja4_fingerprint", "ja4s_fingerprint",
                   "ja4ts_fingerprint", "ja4t_fingerprint"]
    subset_cols = [c for c in subset_cols if c in train_df.columns]

    counts    = train_df.groupby(subset_cols, dropna=False).size().reset_index(name="count")
    unique_df = train_df.drop_duplicates(subset=subset_cols).reset_index(drop=True)
    unique_df = pd.merge(unique_df, counts, on=subset_cols, how="left")

    db_payload = []
    for _, row in unique_df.iterrows():
        db_payload.append({
            "ja4_fingerprint":   row.get("ja4_fingerprint"),
            "ja4s_fingerprint":  row.get("ja4s_fingerprint"),
            "ja4ts_fingerprint": row.get("ja4ts_fingerprint"),
            "ja4t_fingerprint":  row.get("ja4t_fingerprint"),
            "application":       row.get("application"),
            "device":            row.get("device"),
            "library":           row.get("library"),
            "user_agent_string": row.get("user_agent_string"),
            "os":                row.get("os"),
            "count":             int(row["count"]) if "count" in row and pd.notna(row["count"]) else 1,
            "notes":             "Egenlagd Autogenerated",
        })

    # Ensure the directory exists
    os.makedirs(os.path.dirname(output_db_path), exist_ok=True)
    
    with open(output_db_path, "w", encoding="utf-8") as f:
        json.dump(db_payload, f, indent=4, ensure_ascii=True)


# ── Step 2 & 3 · Evaluate TEST samples against a DB ─────────────────────────

def evaluate_test_split_silent(test_df: pd.DataFrame, db_path: str, mode: str, output_file: str):
    import sys, os
    
    # Silence prints from the JA4PlusDatabase load_database method
    old_stdout = sys.stdout
    sys.stdout = open(os.devnull, 'w')
    
    try:
        db = JA4PlusDatabase(mode=mode, db_path=db_path)
        db.load_database()
    finally:
        sys.stdout = old_stdout

    results = []
    for _, row in test_df.iterrows():
        app   = row.get("application", "Unknown")
        ja4   = row.get("ja4_fingerprint") or ""
        ja4s  = row.get("ja4s_fingerprint") or ""
        ja4t  = row.get("ja4t_fingerprint") or ""
        ja4ts = row.get("ja4ts_fingerprint") or row.get("ja4t_fingerprint") or ""

        res = db.predict(ja4=ja4, ja4s=ja4s, ja4t=ja4t, ja4ts=ja4ts)

        prediction  = "Unknown"
        top_k_list  = []
        matches_cnt = 0

        if res.get("result") == "match":
            matches_cnt = res.get("total_unique_combinations_found", 0)
            for m in res.get("top_matches", []):
                cand = m.get("Application")
                if cand and cand not in top_k_list:
                    top_k_list.append(cand)
            if top_k_list:
                prediction = top_k_list[0]

        results.append({
            "true_app":      app,
            "prediction":    prediction,
            "top_k":         top_k_list,
            "matches_count": matches_cnt,
        })

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=4, ensure_ascii=True)

    return results


# ── Step 4 · Generate Visual Charts ───────────────────────────────────────────

def generate_visuals(foxio_res: list, egenlagd_res: list):
    # Attempt to load Iteration 3 results if they exist to fuse into the graph
    rf_res = []
    rf_path = os.path.join(PARENT_DIR, "Iteration3", "Random_Forest_result.json")
    if os.path.exists(rf_path):
        with open(rf_path, 'r', encoding='utf-8') as f:
            rf_res = json.load(f)
            
    # 1. Collision Matrix
    plot_collision_matrix(foxio_res, egenlagd_res, rf_res)
    
    # 2. Top K Accuracy
    plot_top_k(foxio_res, egenlagd_res, rf_res)
    
    # 3. Confusion Matrices
    if foxio_res:
        y_true = [r["true_app"] for r in foxio_res]
        y_pred = [r["prediction"] for r in foxio_res]
        plot_confusion_matrix(y_true, y_pred, "Dictionary_FoxIO")
        
    if egenlagd_res:
        y_true = [r["true_app"] for r in egenlagd_res]
        y_pred = [r["prediction"] for r in egenlagd_res]
        plot_confusion_matrix(y_true, y_pred, "Dictionary_Egenlagd")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import warnings
    warnings.filterwarnings('ignore') # Silence seaborn/pandas warnings
    
    print("Executing Iteration 2 Visual Pipeline...")
    os.makedirs(RESULTS_DIR, exist_ok=True)
    
    print("  [1/4] Loading and splitting dataset...")
    train_df, test_df = load_split_and_plot(DATASET_FILE)

    print("  [2/4] Compiling Egenlagd DB from training split...")
    build_custom_db(train_df, CUSTOM_DB_FILE)

    print("  [3/4] Evaluating Test Split against Models...")
    egenlagd_results = evaluate_test_split_silent(test_df, CUSTOM_DB_FILE, DICT_MODE, EGEN_RESULT_FILE)
    foxio_results    = evaluate_test_split_silent(test_df, FOXIO_DB_FILE, DICT_MODE, FOXIO_RESULT_FILE)

    print("  [4/4] Generating comparative charts...")
    try:
        import sys, os
        old_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')
        generate_visuals(foxio_results, egenlagd_results)
    finally:
        sys.stdout = old_stdout

    print("Success! All iteration 2 visual graphs saved to Dictionary/Visualization/")
